2021-05-22 06:15:56.006 [main] ERROR by.traning.task01.service.Calculation - The number -1.0 did not pass the check
2021-05-22 06:15:56.011 [main] ERROR by.traning.task01.service.Calculation - The number 0.0 did not pass the check
2021-05-22 06:15:56.012 [main] ERROR by.traning.task01.service.Calculation - The number -1.0 did not pass the check
2021-05-22 06:15:56.014 [main] ERROR by.traning.task01.service.Calculation - The number -1.0 did not pass the check
2021-05-22 06:15:56.015 [main] ERROR by.traning.task01.service.Calculation - The number -1.0 did not pass the check
2021-05-22 06:15:56.017 [main] ERROR by.traning.task01.service.Calculation - The number -1.0 did not pass the check
2021-05-22 06:15:56.018 [main] ERROR by.traning.task01.service.Calculation - The number 0.0 did not pass the check
2021-05-22 06:15:56.018 [main] ERROR by.traning.task01.service.Calculation - The number -1.0 did not pass the check
2021-05-22 06:15:56.020 [main] ERROR by.traning.task01.service.Calculation - The number -1.0 did not pass the check
2021-05-22 06:15:56.022 [main] ERROR by.traning.task01.service.Calculation - The number -1.0 did not pass the check
2021-05-22 06:15:56.024 [main] ERROR by.traning.task01.service.Calculation - The number -1.0 did not pass the check
2021-05-22 06:15:56.025 [main] ERROR by.traning.task01.service.Calculation - The number 0.0 did not pass the check
2021-05-22 06:15:56.027 [main] ERROR by.traning.task01.service.Calculation - The number -1.0 did not pass the check
2021-05-22 06:15:56.029 [main] ERROR by.traning.task01.service.Calculation - The number -1.0 did not pass the check
2021-05-22 06:15:56.031 [main] ERROR by.traning.task01.service.Calculation - The number -1.0 did not pass the check
2021-05-22 06:15:56.040 [main] ERROR by.traning.task01.service.Calculation - The number -1.0 did not pass the check
2021-05-22 06:15:56.044 [main] ERROR by.traning.task01.service.Calculation - The number 0.0 did not pass the check
2021-05-22 06:15:56.045 [main] ERROR by.traning.task01.service.Calculation - The number -1.0 did not pass the check
2021-05-22 06:15:56.059 [main] ERROR by.traning.task01.service.Calculation - when summing the value of 2147483647 with a triple, an overflow occurs
2021-05-22 06:15:56.066 [main] ERROR by.traning.task01.service.Calculation - The number -1.0 did not pass the check
2021-05-22 06:15:56.067 [main] ERROR by.traning.task01.service.Calculation - The number -1.0 did not pass the check
2021-05-22 06:15:56.068 [main] ERROR by.traning.task01.service.Calculation - The number -1.0 did not pass the check
2021-05-22 06:15:56.069 [main] ERROR by.traning.task01.service.Calculation - The number -1.0 did not pass the check
2021-05-22 06:15:56.071 [main] ERROR by.traning.task01.service.Calculation - The number -1.0 did not pass the check
2021-05-22 18:25:58.811 [main] ERROR by.traning.task01.dal.FileForDataLogic - readFileToString() is exception.The fileForData FileForData{pathFromContentRoot='src/main/resources/file.txt', file=src\main\resources\file.txt} did not read
2021-05-22 19:01:17.283 [main] ERROR by.traning.task01.dal.FileForDataLogic - readFileToString() is exception.The fileForData FileForData{pathFromContentRoot='src/main/resources/file.txt', file=src\main\resources\file.txt} did not such element
2021-05-22 19:02:51.683 [main] ERROR by.traning.task01.dal.FileForDataLogic - readFileToInt() is exception.The fileForData FileForData{pathFromContentRoot='src/main/resources/file.txt', file=src\main\resources\file.txt} did not such element
2021-05-22 19:02:58.333 [main] ERROR by.traning.task01.dal.FileForDataLogic - readFileToInt() is exception.The fileForData FileForData{pathFromContentRoot='src/main/resources/file.txt', file=src\main\resources\file.txt} did not such element
2021-05-22 19:03:15.076 [main] ERROR by.traning.task01.dal.FileForDataLogic - readFileToInt() is exception.The fileForData FileForData{pathFromContentRoot='src/main/resources/file.txt', file=src\main\resources\file.txt} did not such element
2021-05-22 19:09:08.222 [main] ERROR by.traning.task01.dal.FileForDataLogic - readFileToString() is exception.The fileForData FileForData{pathFromContentRoot='src/main/resources/file.txt', file=src\main\resources\file.txt} did not such element
2021-05-22 19:11:03.357 [main] ERROR by.traning.task01.dal.FileForDataLogic - readFileToString() is exception.The fileForData FileForData{pathFromContentRoot='src/main/resources/file.txt', file=src\main\resources\file.txt} did not such element
2021-05-22 19:11:04.791 [main] ERROR by.traning.task01.dal.FileForDataLogic - readFileToString() is exception.The fileForData FileForData{pathFromContentRoot='src/main/resources/file.txt', file=src\main\resources\file.txt} did not such element
2021-05-22 19:11:37.761 [main] ERROR by.traning.task01.dal.FileForDataLogic - readFileToString() is exception.The fileForData FileForData{pathFromContentRoot='src/main/resources/file.txt', file=src\main\resources\file.txt} did not such element
2021-05-22 19:11:38.578 [main] ERROR by.traning.task01.dal.FileForDataLogic - readFileToString() is exception.The fileForData FileForData{pathFromContentRoot='src/main/resources/file.txt', file=src\main\resources\file.txt} did not such element
2021-05-22 19:11:51.270 [main] ERROR by.traning.task01.dal.FileForDataLogic - readFileToString() is exception.The fileForData FileForData{pathFromContentRoot='src/main/resources/file.txt', file=src\main\resources\file.txt} did not such element
2021-05-22 19:15:48.911 [main] ERROR by.traning.task01.dal.FileForDataLogic - readFileToInt() is exception.The fileForData FileForData{pathFromContentRoot='src/main/resources/file.txt', file=src\main\resources\file.txt} did not such element
2021-05-22 19:16:38.239 [main] ERROR by.traning.task01.dal.FileForDataLogic - readFileToDouble() is exception.The fileForData FileForData{pathFromContentRoot='src/main/resources/file.txt', file=src\main\resources\file.txt} did not such element
2021-05-22 19:17:25.602 [main] ERROR by.traning.task01.dal.FileForDataLogic - readFileToDouble() is exception.The fileForData FileForData{pathFromContentRoot='src/main/resources/file.txt', file=src\main\resources\file.txt} did not such element
2021-05-22 19:23:45.812 [main] ERROR by.traning.task01.dal.FileForDataLogic - readFileToDouble() is exception.The fileForData FileForData{pathFromContentRoot='src/main/resources/file.txt', file=src\main\resources\file.txt} did not such element
2021-05-22 19:25:39.015 [main] ERROR by.traning.task01.dal.FileForDataLogic - readFileToDouble() is exception.The fileForData FileForData{pathFromContentRoot='src/main/resources/file.txt', file=src\main\resources\file.txt} did not such element
2021-05-22 19:25:43.635 [main] ERROR by.traning.task01.dal.FileForDataLogic - readFileToInt() is exception.The fileForData FileForData{pathFromContentRoot='src/main/resources/file.txt', file=src\main\resources\file.txt} did not such element
2021-05-22 19:25:57.391 [main] ERROR by.traning.task01.dal.FileForDataLogic - readFileToInt() is exception.The fileForData FileForData{pathFromContentRoot='src/main/resources/file.txt', file=src\main\resources\file.txt} did not such element
2021-05-22 19:26:40.871 [main] ERROR by.traning.task01.dal.FileForDataLogic - readFileToInt() is exception.The fileForData FileForData{pathFromContentRoot='src/main/resources/file.txt', file=src\main\resources\file.txt} did not such element
2021-05-22 19:33:53.954 [main] ERROR by.traning.task01.dal.FileForDataLogic - readFileToDouble() is exception.The fileForData FileForData{pathFromContentRoot='src/main/resources/file.txt', file=src\main\resources\file.txt} did not such element
2021-05-22 19:34:03.170 [main] ERROR by.traning.task01.dal.FileForDataLogic - readFileToDouble() is exception.The fileForData FileForData{pathFromContentRoot='src/main/resources/file.txt', file=src\main\resources\file.txt} did not such element
